import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';

export async function verifyPagination(page, output, browser) {
  await page.setViewportSize({width:1440,height:1080});
  const review=page.getByRole('button',{name:'下载完整审阅报告',exact:true});
  const ready=async()=>page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent.includes('下载完整审阅报告')&&!b.disabled));
  const plan='version: 1\n\n'+Array.from({length:260},(_,i)=>`dn: cn=target-${i}\nchangetype: modify\nreplace: mail\nmail: secret-${i}\n-\n\n`).join('')+'dn: cn=last-target\nchangetype: delete\n';
  await page.getByLabel('LDIF 源文件内容').fill(plan);
  await page.getByRole('button',{name:'重新检查',exact:true}).click();await ready();
  assert.equal(await page.locator('.results-panel .result-row').count(),50);
  await page.getByRole('button',{name:'下一页',exact:true}).click();
  await page.getByText('第 2 / 6 页',{exact:true}).waitFor();
  await page.getByLabel('跳转页码').fill('6');await page.getByRole('button',{name:'跳转',exact:true}).click();
  await page.getByText('第 6 / 6 页',{exact:true}).waitFor();
  assert.equal(await page.locator('.results-panel .result-row').count(),11);
  await page.getByLabel('查找 DN 或属性').fill('target-2');
  await page.getByLabel('查找 DN 或属性').fill('last-target');
  await page.waitForFunction(()=>document.querySelectorAll('.results-panel .result-row').length===1);
  await ready();
  await page.getByRole('button',{name:'定位删除目录条目',exact:false}).click();
  assert.match(await page.getByLabel('LDIF 源文件内容').evaluate(e=>e.value.slice(e.selectionStart,e.selectionEnd)),/last-target/);
  await page.getByLabel('审阅报告格式').selectOption('json');
  const download=page.waitForEvent('download');await review.click();
  const file=resolve(output,browser+'-complete-tail.json');await (await download).saveAs(file);
  const all=JSON.parse(readFileSync(file,'utf8'));
  assert.equal(all.items.length,261);assert.equal(all.exit_code,1);assert.equal(all.page.selection,'all');
  assert.ok(!JSON.stringify(all).includes('secret-'));
  await page.screenshot({path:resolve(output,browser+'-pagination-desktop.png'),fullPage:true});
  await page.getByLabel('查找 DN 或属性').fill('not-found');
  await page.waitForFunction(()=>document.querySelectorAll('.results-panel .result-row').length===0);await ready();
  assert.ok((await page.locator('.status-strip').innerText()).includes('已拦截'));
  await page.getByRole('button',{name:'迁移前后核对',exact:true}).click();
  const before='version: 1\n\n'+Array.from({length:260},(_,i)=>`dn: cn=${String(i).padStart(3,'0')}\ncn: old\n\n`).join('');
  await page.getByLabel('迁移前快照内容').fill(before);
  await page.getByLabel('迁移后快照内容').fill(before.replaceAll('cn: old','cn: new'));
  await page.getByRole('button',{name:'开始核对',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.snapshot-results .result-row').length===50);
  await page.getByLabel('查找 DN 或属性').fill('cn=259');
  await page.waitForFunction(()=>document.querySelectorAll('.snapshot-results .result-row').length===1);
  await page.getByRole('button',{name:'定位迁移前第',exact:false}).click();
  assert.ok(await page.getByLabel('迁移前快照内容').evaluate(e=>e.selectionStart>1000));
  await page.getByLabel('核对报告格式').selectOption('json');
  const snapDownload=page.waitForEvent('download');await page.getByRole('button',{name:'下载完整核对报告',exact:true}).click();
  const snapFile=resolve(output,browser+'-complete-snapshot.json');await (await snapDownload).saveAs(snapFile);
  assert.equal(JSON.parse(readFileSync(snapFile,'utf8')).items.length,260);
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:resolve(output,browser+'-pagination-mobile.png'),fullPage:true});
  await page.getByRole('button',{name:'文件预检',exact:true}).click();
  assert.equal(await review.isEnabled(),false);
  assert.equal(await page.getByLabel('LDIF 源文件内容').inputValue(),plan);
}
