import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';

export async function verifyProfiles(page,output,browser) {
  await page.setViewportSize({width:1440,height:1080});
  await page.getByRole('button',{name:'文件预检',exact:true}).click();
  const section=page.getByRole('region',{name:'预检配置',exact:true});
  const ready=()=>page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent.includes('下载完整审阅报告')&&!b.disabled));
  const raw=JSON.stringify({profile_version:1,review:{limits:{max_delete_records:5}},compare:{ignored_attributes:['cn']}});
  await page.getByLabel('加载预检配置',{exact:true}).setInputFiles({name:'rules.json',mimeType:'application/json',buffer:Buffer.from(raw)});
  await section.getByText('已加载配置',{exact:false}).waitFor();
  assert.equal(await page.getByRole('button',{name:'下载完整审阅报告',exact:true}).isEnabled(),false);
  assert.equal(await page.getByLabel('拦截整条删除',{exact:true}).isChecked(),false);
  const data='version: 1\n'+Array.from({length:6},(_,i)=>`dn: cn=profile-${i}\nchangetype: delete\n\n`).join('');
  await page.getByLabel('LDIF 源文件内容').fill(data);
  await page.getByRole('button',{name:'重新检查',exact:true}).click();await ready();
  await section.getByText('最多整条删除：6 / 5',{exact:false}).waitFor();
  await section.getByRole('button',{name:'定位越界'}).click();
  assert.match(await page.getByLabel('LDIF 源文件内容').evaluate(e=>e.value.slice(e.selectionStart,e.selectionEnd)),/profile-5/);
  assert.equal(await page.getByRole('button',{name:'导出新文件',exact:true}).isEnabled(),false);
  await page.getByLabel('审阅报告格式').selectOption('json');
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'下载完整审阅报告',exact:true}).click();
  const file=resolve(output,browser+'-profile-report.json');await (await download).saveAs(file);
  const report=JSON.parse(readFileSync(file,'utf8'));
  assert.equal(report.report_schema_version,3);assert.equal(report.exit_code,1);assert.equal(report.items.length,6);
  assert.equal(report.summary.profile.source_sha256,createHash('sha256').update(raw).digest('hex'));
  assert.equal(report.summary.profile.effective_sha256,createHash('sha256').update(JSON.stringify(report.summary.profile.effective)).digest('hex'));
  await page.getByLabel('最多整条删除',{exact:true}).fill('6');
  assert.equal(await page.getByRole('button',{name:'下载完整审阅报告',exact:true}).isEnabled(),false);
  await page.getByRole('button',{name:'重新检查',exact:true}).click();await ready();
  assert.equal(await page.getByRole('button',{name:'导出新文件',exact:true}).isEnabled(),true);
  const configDownload=page.waitForEvent('download');await section.getByRole('button',{name:'下载当前配置'}).click();
  const configFile=resolve(output,browser+'-profile.json');await (await configDownload).saveAs(configFile);
  assert.equal(JSON.parse(readFileSync(configFile,'utf8')).review.limits.max_delete_records,6);
  const editedDownload=page.waitForEvent('download');await page.getByRole('button',{name:'下载完整审阅报告',exact:true}).click();
  const editedFile=resolve(output,browser+'-profile-edited.json');await (await editedDownload).saveAs(editedFile);
  const edited=JSON.parse(readFileSync(editedFile,'utf8'));
  assert.equal(edited.summary.profile.source_sha256,'');assert.equal(edited.exit_code,0);
  assert.equal(edited.summary.profile.effective_sha256,createHash('sha256').update(JSON.stringify(edited.summary.profile.effective)).digest('hex'));
  await page.screenshot({path:resolve(output,browser+'-profile-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:resolve(output,browser+'-profile-mobile.png'),fullPage:true});
  await page.getByLabel('加载预检配置',{exact:true}).setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"profile_version":1,"profile_version":1}')});
  await section.getByRole('alert').waitFor();
  assert.equal(await page.getByRole('button',{name:'重新检查',exact:true}).isEnabled(),false);
  assert.equal(await page.getByRole('button',{name:'下载完整审阅报告',exact:true}).isEnabled(),false);
  await section.getByRole('button',{name:'停用配置'}).click();
  await page.getByRole('button',{name:'迁移前后核对',exact:true}).click();
  const comparison=page.getByRole('region',{name:'核对配置',exact:true});
  await page.getByLabel('加载核对配置',{exact:true}).setInputFiles({name:'rules.json',mimeType:'application/json',buffer:Buffer.from(raw)});
  await comparison.getByText('已加载配置',{exact:false}).waitFor();
  await page.getByLabel('迁移前快照内容').fill('version: 1\ndn: cn=a\ncn: old\n');
  await page.getByLabel('迁移后快照内容').fill('version: 1\ndn: cn=a\ncn: new\n');
  await page.getByRole('button',{name:'开始核对',exact:true}).click();
  await page.getByText('当前比较规则下未发现差异',{exact:true}).waitFor();
  const diffDownload=page.waitForEvent('download');await page.getByLabel('核对报告格式').selectOption('json');await page.getByRole('button',{name:'下载完整核对报告',exact:true}).click();
  const diffFile=resolve(output,browser+'-profile-diff.json');await (await diffDownload).saveAs(diffFile);
  const diff=JSON.parse(readFileSync(diffFile,'utf8'));assert.equal(diff.report_schema_version,3);assert.equal(diff.summary.profile.applied_section,'compare');
  await comparison.getByRole('button',{name:'停用配置'}).click();
  // A slow file read must not overwrite a newer configuration or survive a mode switch.
  await page.evaluate(()=>{
    const original=File.prototype.arrayBuffer;
    File.prototype.arrayBuffer=async function(){if(this.name==='slow-profile.json')await new Promise(r=>setTimeout(r,400));return original.call(this);};
  });
  await page.getByRole('button',{name:'文件预检',exact:true}).click();
  await page.getByLabel('加载预检配置',{exact:true}).setInputFiles({name:'slow-profile.json',mimeType:'application/json',buffer:Buffer.from(raw)});
  await page.getByLabel('加载预检配置',{exact:true}).setInputFiles({name:'new-profile.json',mimeType:'application/json',buffer:Buffer.from('{"profile_version":1,"review":{"limits":{"max_delete_records":2}}}')});
  await section.getByText('已加载配置',{exact:false}).waitFor();
  await page.waitForTimeout(600);
  assert.equal(await page.getByLabel('最多整条删除',{exact:true}).inputValue(),'2');
  await page.getByLabel('加载预检配置',{exact:true}).setInputFiles({name:'slow-profile.json',mimeType:'application/json',buffer:Buffer.from(raw)});
  await page.getByRole('button',{name:'迁移前后核对',exact:true}).click();
  await page.waitForTimeout(600);await page.getByRole('button',{name:'文件预检',exact:true}).click();
  assert.equal(await page.getByLabel('最多整条删除',{exact:true}).inputValue(),'2');
  assert.equal(await page.getByRole('button',{name:'下载完整审阅报告',exact:true}).isEnabled(),false);
  await section.getByRole('button',{name:'停用配置'}).click();
  return ['profile-import-export','profile-limit-navigation','profile-effective-fingerprint','profile-edited-source-invalidation','profile-compare-scope','profile-invalid-blocked','profile-read-races'];
}
